### ISSUE TITLE
Plugin should be installable via "docker plugin install"

### ISSUE THREAD

**Issue by holgerstolzenberg** [MatchbookLab/local-persist#54]

**Comment by nickbreen** [comment]
There is no way to dynamically set bind mounts for a plugin container as they are defined in the `config.json` plugin spec. 

We'll be limited to bind mounting under a FHS-ish path, say `/var/lib/docker-local-persist/volumes` or `/var/run/docker-local-persist/volumes`; not unlike docker itself that stores its volumes in `/var/lib/docker/volumes'.

Anyone can still bind mount or symlink the directory elsewhere if they want to.

**Comment by CWSpear** [comment]
So there is a way to have "config" for your plugin, and you can change that stuff via config. But it's kind of a pain, and I was looking to see if I could find a better way (and then got distracted again and never followed up).

**Comment by CWSpear** [comment]
The syntax is something like:

```
docker plugin set local-persist volumes.source=/path/to/folder/ volumes.destination=/path/to/folder/
```

The reason I especially don't like this solution is that you can only have one path for _all_ projects, and all volumes would have to be sub-directories of that. That works for how I do it personally, but probably not for a lot of people.

I also have to set a default... I wouldn't want to mess someone up who didn't realize there was a default and compromise data or something (on my `docker-plugin` branch, I have it default to `/data/` for both source and destination).

I could add extra config settings, like `volumes1.source`, `volumes2.source`, etc... but that's really messy and there doesn't seem a way to handle `n` volumes.

**Comment by vicary** [comment]
Is it possible to defaults to the behavior exactly as the `local` driver does, until there is a mount point configured?

**Comment by CWSpear** [comment]
Not really? The thing about a Docker Plugin, is the plugin runs inside a container. So it has the same limitations as other containers... you can't share data between them without explicit volume mapping. It's worse in this case cuz all the volume matching have to match... it has to be the same exact path on the host as well as in the container.
