### ISSUE TITLE
cannot remove local-persist volume

### ISSUE THREAD

**Issue by kspoon01** [MatchbookLab/local-persist#66]
>docker volume rm etfdb_pgdata
Error response from daemon: get etfdb_pgdata: error while checking if volume "etfdb_pgdata" exists in driver "local-persist": Post http://%2Frun%2Fdocker%2Fplugins%2Flocal-persist.sock/VolumeDriver.Get: dial unix /run/docker/plugins/local-persist.sock: connect: connection refused

docker version is 18.09.0, build 4d60db4

I am pretty new to docker, please let me know what else I should provide.

Why is it trying to access the web?

**Comment by devopsn** [comment]
I met with the same problem, restarting the docker helped me.

**Comment by datocrats-org** [comment]
Related concern, if for any reason in the future developers were told to no longer use local-persist as a driver in docker-compose for example, how would you recommend migrating back to named volumes using another "driver"? Is that possible?

**Comment by CWSpear** [comment]
@datocrats-org You just move the actual data wherever that other driver supports... nothing magic or special here.

**Comment by CWSpear** [comment]
@kspoon01 you've definitely move on from here, but it's trying to access the socket, which is how it communicates. Maybe something was configured wrong that you had it looking at the wrong address or something.

**Comment by taeun0** [comment]
I have a same issue. I am trying run local-persist and occurs same meesage. Has anyone solved this problem?
Is it occurs because volume name already exists?
I tried this.

```bash
$ docker volume create -d local-persist -o mountpoint=/{path} mongo-configsvr-data
Error response from daemon: create mongo-configsvr-data: found reference to volume 'mongo-configsvr-data' in driver 'local-persist', but got an error while checking the driver: error while checking if volume "mongo-configsvr-data" exists in driver "local-persist": Post http://%2Frun%2Fdocker%2Fplugins%2Flocal-persist.sock/VolumeDriver.Get: dial unix /run/docker/plugins/local-persist.sock: connect: connection refused: volume name must be unique

$ docker volume ls
DRIVER              VOLUME NAME
local-persist       mongo-configsvr-data
```

**Comment by taeun0** [comment]
> I have a same issue. I am trying to run local-persist and occurs same meesage. Is there anyone solved this problem? Is it occurs because volume name already exists? I tried this.
> 
> ```shell
> $ docker volume create -d local-persist -o mountpoint=/{path} mongo-configsvr-data
> Error response from daemon: create mongo-configsvr-data: found reference to volume 'mongo-configsvr-data' in driver 'local-persist', but got an error while checking the driver: error while checking if volume "mongo-configsvr-data" exists in driver "local-persist": Post http://%2Frun%2Fdocker%2Fplugins%2Flocal-persist.sock/VolumeDriver.Get: dial unix /run/docker/plugins/local-persist.sock: connect: connection refused: volume name must be unique
> 
> $ docker volume ls
> DRIVER              VOLUME NAME
> local-persist       mongo-configsvr-data
> ```

In my case, we solved it by restarting docker process. Maybe it seems to be a docker problem...😓

**Comment by taeun0** [comment]
thank you for reply!

**Comment by andycarlberg** [comment]
Sorry to hit such an old issue but it's the only reference to my problem I've been able to find.

I'm getting this error when trying to create a new volume with the local-persist driver.
```
Error response from daemon: create new_volume: error looking up volume plugin local-persist: legacy plugin: Post "http://%2Frun%2Fdocker%2Fplugins%2Flocal-persist.sock/Plugin.Activate": dial unix /run/docker/plugins/local-persist.sock: connect: connection refused
```
