### ISSUE TITLE
linux armv6l is not supported

### ISSUE THREAD

**Issue by utdrmac** [MatchbookLab/local-persist#67]
Please support this plugin on RaspberryPi

```
# curl -fsSL https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh | sudo bash
linux armv6l is not supported
```

**Comment by dash042** [comment]
I agree. ARM support is a MUST-HAVE...

**Comment by CWSpear** [comment]
Someone created a PR with some promise, but hasn't responded to my feedback and there was a couple (at least one major) concerns I had with the PR and he hasn't responded and I haven't followed up. See PR https://github.com/CWSpear/local-persist/pull/63

**Comment by CWSpear** [comment]
https://github.com/MatchbookLab/local-persist/pull/88 should cover it. I haven't added binaries yet, so the installer may not work, but the support is there.
