### ISSUE TITLE
Request: aarch64 support

### ISSUE THREAD

**Issue by EvolverDX** [MatchbookLab/local-persist#87]
I recently switched to a new raspberry pi 4 and I use the 64bit OS-version now. 
So I want to request a aarch64 support for this awesome docker plug-in.

**Comment by MaurizioB84** [comment]
up

**Comment by anshuman852** [comment]
up

**Comment by nullLyfe** [comment]
Looks like there is a PR open to add support to arm64 but it has not been approved to merge with the master branch.

**Comment by xsolinsx** [comment]
up

**Comment by DunkelAmber** [comment]
up

**Comment by CWSpear** [comment]
Added. See https://github.com/MatchbookLab/local-persist/pull/88
